### ISSUE TITLE
Please provide a guide to set up the Google credentials

### ISSUE THREAD

**Issue by Vacilando** [Kornil/gatsby-plugin-google-analytics-reporter#2]
The "guide here" link at https://github.com/Kornil/gatsby-plugin-google-analytics-reporter/blob/master/README.md is empty.

**Comment by Kornil** [comment]
Added link to README! Thank you for reporting it!

Guide is here -> https://decodenatura.com/how-to-add-a-trending-section-to-gatsby-blog/
