### ISSUE TITLE
Option to have two start dates

### ISSUE THREAD

**Issue by mbcod3** [Kornil/gatsby-plugin-google-analytics-reporter#7]
Is it possible to have two sets of data. All time data with very old start date and last 30 day data like your example?

**Comment by Kornil** [comment]
Not at the moment I believe, but it might be possible to support multiple date ranges here https://github.com/Kornil/gatsby-plugin-google-analytics-reporter/blob/master/gatsby-node.js#L28. We'd have to support that also on the user side so the different date ranges can be used. Wanna try to make an MVP of how you'd like the feature to be implemented?

**Comment by Kornil** [comment]
Closing for now, feel free to reopen if there's progress!
