### ISSUE TITLE
Support Gatsby v4

### ISSUE THREAD

**Issue by Vacilando** [Kornil/gatsby-plugin-google-analytics-reporter#8]
Please update to support Gatsby v4.

When using this module, some keys are too long and cause error "Key is larger than maximum key size (1978)" in LMDB - see https://github.com/gatsbyjs/gatsby/discussions/33887

**Comment by Kornil** [comment]
I'm going to investigate this in the coming days.

**Comment by Vacilando** [comment]
Apparently LMDB cannot accept keys longer than 1978 characters. In case of gatsby-plugin-google-analytics-reporter this happens sometimes - I've seen cases where the relative URL fetched from analytics had many or too long arguments. Often the URL-encoding added to the length as well (/page?title=%2525252525 ...).

Such long relative URLs are not useful and happen rarely, but they break the functionality of this plugin when using LMBD, so definitely in Gatsby v4.
I would simply suggest to truncate or even drop such URLs if they are longer than what LMDB currently supports (1978).

**Comment by Vacilando** [comment]
See https://github.com/gatsbyjs/gatsby/discussions/33887 - the solution might be simple enough:

> In this instance the plugin is at fault as the id should be generated with `createNodeId()`.
> Instead of passing the full path as an id it should use the `createNodeId()` helper function:
> https://github.com/Kornil/gatsby-plugin-google-analytics-reporter/blob/7ae7c6f67f880c0311645d5ef369bb749a100054/gatsby-node.js#L63
> Helper function: https://www.gatsbyjs.com/docs/reference/config-files/node-api-helpers/#createNodeId
> Truncating the path before passing it into `createNodeId()` is probably not necessary.
